### ISSUE TITLE
reference to DIN/TS 5031-100 not correct for non-melanopic assessments

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#10]
on the pages for erythropic, chloropic, cyanopic and rhodopic assessment, there is a hint:
the weighing is compliant with the [DIN/TS 5031-100:2021-11.](https://www.beuth.de/de/vornorm/din-ts-5031-100/343737176)

this is not correct, as DIN/TS 5031-100 does not define weighting functions other than the melanopic. 

The reference should cite CIE S 026 instead of DIN/TS 5031-100
And of course the naming should refer to S-, M- and L-cones

**Comment by JZauner** [comment]
While the DIN/TS 5031-100:2021-11 does not define the weighting functions of the other receptor types, in 5.2 it does mention that you should look to CIE TN 011:2020 for parameters to document, which in turn says that all 5 alpha-opic domains from CIE S026 should be reported, at least in laboratory studies.
This tells me, that if I do that, I am compliant with the DIN/TS´s suggestion, no? I´am happy to change the wording of the statement, if you have other suggestions. 
(and I will change the references to S-, M- and L-cones)

**Comment by DieterLa** [comment]
I think you should always cite the primary reference.
This is CIE S 026.
For the German version it may be ok to show DIN/TS 5031-100 as reference for MEDI and MDER. But if English or other language versions will be chosen, it should be CIE.
For other responses than melanopic it should be CIE S026 also in the German language version, because the pathway from DIN/TS via CIE TN 003 to CIE S 026 is too indirect.



______________________________________

sent by my mobile phone  +49 151 61 666 362

Dieter Lang
R&D & Innovation Expert Human Centric Lighting

Ledvance GmbH
Parkring 33

85748 Garching
Deutschland/Germany
Mobile: +49 151 61 666 362(preferred calling option)
Phone : +49 89 780673 277  (new number for extension!)

E-mail : ***@***.******@***.***>

Check out our information on the BIOLUX Human Centric Lighting system
https://www.ledvance.com/professional/products/product-stories/human-centric-lighting/index.jsp


LEDVANCE GmbH: Chairperson of the Supervisory Board: Yan Luo; Managing Directors: Qinghuan Sun, Shi-Ting Chu, Tingfeng Mei;



Registered office: Garching near Munich; Commercial registry: Munich, HRB 220074; WEEE-Reg.-No. DE 30638372

________________________________
Von: Johannes Zauner ***@***.***>
Gesendet: Friday, September 15, 2023 10:17:15 AM
An: LiTGde/Spectran ***@***.***>
Cc: Lang, Dieter ***@***.***>; Author ***@***.***>
Betreff: Re: [LiTGde/Spectran] reference to DIN/TS 5031-100 not correct for non-melanopic assessments (Issue #10)


While the DIN/TS 5031-100:2021-11 does not define the weighting functions of the other receptor types, in 5.2 it does mention that you should look to CIE TN 011:2020 for parameters to document, which in turn says that all 5 alpha-opic domains from CIE S026 should be reported, at least in laboratory studies.
This tells me, that if I do that, I am compliant with the DIN/TS´s suggestion, no? I´am happy to change the wording of the statement, if you have other suggestions.
(and I will change the references to S-, M- and L-cones)

**Comment by JZauner** [comment]
I removed the reference from alphaopic weighing. It will go online in Version 1.0.0 of Spectran
