### ISSUE TITLE
Reference to CIE S 026 not correct for age-correction related to pupil size

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#11]
Only DIN/TS 5031-100 defines an age-correction for reduced pupil diameter with age. 
CIE S 026 doesn't define this. 
For this correction, the reference should only cite DIN, but not CIE. 

This applies on all results pages for age-corrected data

**Comment by JZauner** [comment]
I guess this goes back to the previous issue #10 , just the other way around. Both DIN and CIE say that age correction should be considered, but only DIN provides the equation. 
Right now, Spectran states that: "The equations for the age-related correction are taken from DIN/TS 5031-100:2021-11. The evaluation is further compliant with the CIE S026 (2018)."
This to me still makes sense, as when I apply the age-correction from DIN/TS, I comply with the requirement for age-correction from CIE, no?

**Comment by JZauner** [comment]
Made the change. It will go online in Version 1.0.0 of Spectran
