### ISSUE TITLE
Age-correction gives different values as mentioned in simplified formula (23) of DIN/TS 5031-100

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#12]
DIN/TS 5031-100 has introduced a simplified formula for the lens-transmittance (eq. 23) 
Spectran calculates correctly according to the complete formula (20).
A hint should be included in the results-pages, that the calculations for lens-transmittance are based on the complete and not on the simplified formula. 
This is also compliant with CIE S 026, which does not use the simplified method.

**Comment by JZauner** [comment]
I can include this. There is already some Background Information in a Dropdown at the Top, where I can easily add this.

**Comment by JZauner** [comment]
Made the change. It will go online in Version 1.0.0 of Spectran
