### ISSUE TITLE
photons / quanta / quanta of radiation

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#13]
I am not 100% sure about the following: 

you are using the unit quanta/(cm^2 * s) for photon flux density. 
This is the same as  photon irradiance 
this is basically correct. 
But I am not sure if quanta alone is correct. The term "quanta" alone may be clear to a physicist, active in assessment of radiation. 

I am wondering if not photons/(cm^2 * s) would be better. 
also possible: 
number of photons/(cm^2 * s) or quanta of radiation/(cm^2 * s)

The SI unit would be 1/(m^2 * s)
The term "photon" or "quanta" is not a unit and is used only to make clear, what it is. 

Earlier the term µEinstein or µmols  has been used to express this quantity related to a mol of photons, but this is no longer supported by SI.

**Comment by JZauner** [comment]
I mainly used quanta because in most publications of non-visual effects of light this was used rather than photons, but I agree that photons are more relatable to other fields. I will change this.

**Comment by JZauner** [comment]
Made the change. It will go online in Version 1.0.0 of Spectran
