### ISSUE TITLE
OPN4/smel   on the page for melanopic evaluation 

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#15]
OPN4 is the pure molecule. But the sensitivity in smel(λ) is age-corrected for a 32 years old human. 
I would prefer to drop the reference to OPN4 on this page.

the mel in smel should be written as subscript.  Sorry, I couldn't realize it here.

**Comment by DieterLa** [comment]
s<sub>mel</sub>(λ)

that's how it should look like

**Comment by JZauner** [comment]
I see your point and will change it.

**Comment by JZauner** [comment]
made the change - will go online with Version 1.0.0. of Spectran
