### ISSUE TITLE
Negative Ri values are not readable within the diagram

### ISSUE THREAD

**Issue by Kenneth-M-Zgroup** [LiTGde/Spectran#16]
![2023_11_03_13_34_15_Spectran](https://github.com/LiTGde/Spectran/assets/128629561/839371c5-d412-495c-9269-78a20e3fb59d)
[722negR9Test.csv](https://github.com/LiTGde/Spectran/files/13250227/722negR9Test.csv)
When a spectral distribution has negative e.g. R9 values, those are not displayed as a number in the diagram.
(already mentioned in my feedback email to spectran@litg.de on Tuesday the 5th of Sept. 2023)

**Comment by JZauner** [comment]
<img width="720" alt="Bildschirmfoto 2023-11-03 um 17 35 36" src="https://github.com/LiTGde/Spectran/assets/112665672/68c4f5cd-d868-4915-a1f7-ce07e022d049">

Hi Kenneth! Thanks for your reminder. I fixed the bug and it will go online shortly, when we release Spectran outside of Beta. Thank you also for your other feedback - we will take all of it into due consideration. At present, however, we focus on bugs, while feature requests will be tackled at a later point.
