### ISSUE TITLE
Decide and inform user about units for data import  mW/nm or W/nm

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#4]
The input assumes the data given in W/nm
Results are shown in mW/nm
This is not consistent
Best option would be allowing the user to decide about his data. 
second best option is to inform the user about the required scaling in W/nm
Often data is saved in mW/nm

**Comment by JZauner** [comment]
Actually, the second sentence in the import/Upload section states that data needs to be in` W/(m² * nm)`, so the second best option is already included. 
Rescaling can be easily done in the `Import Options`. I think the easiest way to implement your best option would be to just make a little selection available there to state how the data is scaled. I can do that.

**Comment by JZauner** [comment]
I have added an option to set the import format to mW, to W, or to your own scale. It will go online in Version 1.0.0 of Spectran
