### ISSUE TITLE
CRI is not available

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#6]
Is CRI (Ra) not calculated, or just not available in the case which I tested. 
Result should be CRI = 81, but only  NA is shown

**Comment by NilesDavis** [comment]
Could you provide the SPD you tested? The CRI computation could fail due to invalid CCT or Delta uv and this should be the main reason for it to be NA.
Or is it that we should print "not computable due to ..." instead of NA?

**Comment by DieterLa** [comment]
[Beispiel (1).csv](https://github.com/LiTGde/Spectran/files/12466677/Beispiel.1.csv)

this is the spectrum of a cold-white fluorescent lamp; unit is in µW/nm
CCT is high, but in a reasonable range and in a well-defined range. 
The deviation in the CCT calculation is obvious, but appears not too critical. Even if it shouln't happen.


results of Spectran:
Correlated Color Temperature	CCT	    9.085	K
Color Rendering Index	Ra	NA	

my own results for CRI
RA	81
R1	96
R2	91
R3	40
R4	88
R5	92
R6	73
R7	83
R8	87
R9	77
R10	39
R11	76
R12	58
R13	97
R14	61
x	0,2915
y	0,2835
CCT	9063
dC_SWE	-9,43
x-Ref	0,2852
y-Ref	0,2994
CCT-Ref	9000
dC-Ref_SWE	12,48

**Comment by DieterLa** [comment]
I uploaded the spectrum in a comment to the issue#6

I think you should try to find the reason for failing to calculate CRI, because this is not an extreme spectrum, even if it is quite blueish.

**Comment by JZauner** [comment]
I tested the spectrum you uploaded. Indeed, it exceeds the CIE limits for CCT and CRI calculations. If you deactivate the checkbox to use CIE limits, it shows an Ra of 81. Spectran also states this . So I guess this is correct behaviour.
<img width="1073" alt="Bildschirmfoto 2023-09-15 um 09 43 34" src="https://github.com/LiTGde/Spectran/assets/112665672/977a2f9a-3076-4724-91a6-74adef99dce7">
<img width="1079" alt="Bildschirmfoto 2023-09-15 um 09 43 30" src="https://github.com/LiTGde/Spectran/assets/112665672/6137f430-1a28-4806-a583-18591dcfa69d">

**Comment by JZauner** [comment]
closing this issue, as the output shows correct behavior
