### ISSUE TITLE
sign for decimal separator

### ISSUE THREAD

**Issue by DieterLa** [LiTGde/Spectran#8]
In standards, independent from their language, a comma "," is used as decimal separator. 
No sign is used for thousands-separator. 
But all numbers are written in groups of three numbers. 
e.g.  4 123 000,987 6 
Please consider using this standardized format for your output

**Comment by JZauner** [comment]
I will implement this.

**Comment by JZauner** [comment]
Made the change. It will go online in Version 1.0.0 of Spectran
